spring.application.name=hospital-management-system

spring.datasource.url=jdbc:mysql://localhost:3306/hospital_db
spring.datasource.username=root
spring.datasource.password=manas


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


server.port=8080